### ISSUE TITLE
Error using autocomplete with aurelia-cli

### ISSUE THREAD

**Issue by GunsAkimbo** [drivesoftware/aurelia-autocomplete#10]
Hi,

I'm having issues with this module with an aurelia-cli based project.

I get this error in the browser console when I load the application:
```
Uncaught TypeError: Cannot read property '__useDefault' of undefined
    at ensureOriginOnExports (vendor-bundle.js:13786)
    at vendor-bundle.js:13894
    at Object.execCb (vendor-bundle.js:5484)
    at Module.check (vendor-bundle.js:4671)
    at Module.enable (vendor-bundle.js:4964)
    at Module.init (vendor-bundle.js:4576)
    at vendor-bundle.js:5248
```
No errors are displayed during compilation and bundling. The error also appears even if i comment out the autocomplete-tags i app.html, so I believe this error is related to installation/reference to the autocomplete module. 

Can you see what's wrong? Do you have a live demo somewhere? Or a download link with a working project?

This is my configuration:

package.json:
```json
"dependencies": {
    "aurelia-autocomplete": "git+https://github.com/drivesoftware/aurelia-autocomplete.git"
}
```

aurelia.json:
```json
{
  "name": "aurelia-autocomplete",
  "main": "index",
  "path": "../node_modules/aurelia-autocomplete/dist/amd",
  "resources": [
  "autocomplete.css"
  ]
}
```

main.ts:
```typescript
export function configure(aurelia: Aurelia) {
  aurelia.use
    .standardConfiguration()
    .feature('resources')
    .plugin('aurelia-autocomplete');

  aurelia.start().then(() => aurelia.setRoot());
}
```

app.ts:
```typescript
import { autoinject } from 'aurelia-dependency-injection';
import { ClientAPI } from './client-api';
import { AutoCompleteController } from 'aurelia-autocomplete';

@autoinject()
export class App {
  client: any;
  constructor(private clientAutoCompleteController: AutoCompleteController, private clientApi: ClientAPI) {
    clientAutoCompleteController = new AutoCompleteController((searchText) => this.clientApi.suggestNames(searchText));
  }
}
```

app.html:
```html
<template>
  <require from="bootstrap/css/bootstrap.css"></require>
  
  <autocomplete value.bind="client" controller.bind="clientAutoCompleteController">
    <template replace-part="suggestion"><strong>${suggestion.nameID}</strong> ${suggestion.name}</template>
  </autocomplete>
</template>
```

**Comment by simonfox** [comment]
@GunsAkimbo I need to make some changes to the build as currently the `aurelia.json` configuration needs to be

```
{
   "name": "aurelia-autocomplete",
   "main": "index",
   "path": "../node_modules/aurelia-autocomplete/dist/amd",
   "resources": [
      "*.js",
      "*.html",
      "autocomplete.css"
   ]
},
```

Can you let me know if that solves the problem?

**Comment by GunsAkimbo** [comment]
Thank you, that worked. 

Another thing, I want to display the `name` property in the list and in the input field, however, I am actually interested in the `id` property. The ids should not be displayed as they are guid values, so not user friendly. How do I achieve that?

edit: never mind, once I understood the binding object, I solved it.

**Comment by simonfox** [comment]
@GunsAkimbo [see here](https://github.com/drivesoftware/aurelia-autocomplete#autocompletecontroller) - if you replace the `formatSuggestion` function on your controller you can change the displayed text of the selection.
