### ISSUE TITLE
Running tests on the Autocomplete component

### ISSUE THREAD

**Issue by vidaritos** [drivesoftware/aurelia-autocomplete#13]
Hi, I want to extend some functionality into the component, but I'm having a difficult time instantiating the Autocomplete-class to start unit testing. Using nulls in the constructor fails. Are you able to add a working test of the Autocomplete-class?

Edit: what I want to add is a new bindable parameter that enables/disables the automatic select whenever a single suggestion is returned. [autocomplete.js:95](https://github.com/drivesoftware/aurelia-autocomplete/blob/master/src/autocomplete.js#L95)

**Comment by simonfox** [comment]
Hi @vidaritos thanks for your interest...that feature sounds like a good idea!

Test state is pretty bad currently, sorry about that. I'm quite busy right now, but the following might help you get started via the `aurelia-testing` library....

First you'll need to install some missing dependencies (I have omitted for brevity here but some of these should be dev deps).
```
jspm i aurelia-testing
jspm i aurelia-bootstrapper
jspm i aurelia-pal-browser
jspm i aurelia-loader-default
```

Then update `karma.conf.js` to ensure jspm/systemjs loads html files (for the template) 
```
...
jspm: {
      // Edit this to your needs
      loadFiles: ['test/setup.js', 'test/unit/**/*.js'],
      serveFiles: ['src/**/*.js', 'src/**/*.html'],
...
```

Then you should be able to get the thing up and running with a test like the following
``` test/unit/autocomplete.spec.js
import { StageComponent, ComponentTester } from 'aurelia-testing';
import { bootstrap } from 'aurelia-bootstrapper';
import { AutoCompleteController } from '../../src/autocompletecontroller';

describe('autocomplete', () => {
  const controller = new AutoCompleteController(() => Promise.resolve());
  let component;

  beforeEach(() => {
    component = StageComponent
      .withResources('src/autocomplete')
      .inView(`<autocomplete value.bind="client"
                            title.bind="label" 
                            controller.bind="clientAutoCompleteController"></autocomplete>`);

    component.bootstrap(aurelia => {
      return aurelia.use
        .standardConfiguration();
    });
  });

  it('should set the label to the value title is bound to', (done) => {
    let client = null;
    let label = "A Client Label";

    component.boundTo({ label, client, controller });
    component.create(bootstrap)
      .then(() => {
        const labelEl = document.querySelector('label');
        expect(labelEl.innerHTML).toBe(label);

        done();
      })
      .catch((ex) => done.fail(ex));
  });
});
```

Let me know if you run into any issues with this...
