### ISSUE TITLE
Input field gets cleared/freeze/blocked while typing on IE11

### ISSUE THREAD

**Issue by maximedubois** [drivesoftware/aurelia-autocomplete#15]
Whenever I use your autocomplete on Chrome, Edge it works fine. If I use it in IE11, when I start typing I get blocked and cannot continue typing. When the response is received from the server with the suggestions whatever was in the input filed gets cleared and the suggestions do not appears. I can start typing again once the field is cleared.

**Comment by simonfox** [comment]
@maximedubois thanks for reporting, however I am unable to reproduce. Are you able to provide a little more detail?

**Comment by maximedubois** [comment]
here's a repo I created simple aurelia project with your autocomplete to reproduce.
From what I can see there's a kind of delay of being able to type before the list shows the result. Once the result is displayed in the list then I'm able to start typing again. When using real api that might have a delay before getting an answer it's getting worse. 

The issue is really with Internet Explorer 11. That effect is not visibile in Chrome or Edge.

https://github.com/maximedubois/aurelia-autocomplete-ie11-issue.git

**Comment by simonfox** [comment]
@maximedubois ok there is some native code in IE that is just thrashing.....if you add corejs (on our app we use 2.5.3).....

`yarn add core-js@2.5.3`

and then add to prepend in aurelia.json....

`"node_modules/core-js/client/core.js"`

Performance is great so there must be some polyfill there that is fixing it......you could possibly try using the [aurelia-polyfills](https://www.npmjs.com/package/aurelia-polyfills) package as it may achieve the same results if you don't want to add corejs dependency.

**Comment by simonfox** [comment]
@maximedubois hopefully this answers your question? Going to close for now, please let me know if you still have any troubles...
